import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { auth, currentUser, EmailAddress } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar
            clerkUserId={userId}
            user={{
              id: user?.id,
              username: user?.username,
              imageUrl: user?.imageUrl,
              firstName: user?.firstName,
              lastName: user?.lastName,
              emailAddresses: user?.emailAddresses[0].emailAddress,
            }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
